CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255),
    pin_code VARCHAR(10),
    face_embedding CLOB,
    created_at TIMESTAMP
);
INSERT INTO users (username, full_name, pin_code, face_embedding, created_at)
VALUES ('legacy', 'Legacy fixture', '001234', '[1,2,3]', '2026-01-01 00:00:00');
